### PR TITLE
Introduce `useTimezoneSelect` hook

### PR DESCRIPTION
**Pull request by DreierF**
### Description

This PR implements a solution for the issue discussed in #64.
I basically extracted a hook named `useTimezoneSelect` out of `TimezoneSelect` that exposes the options creation and the `parseTimezone` function to allow using other UI implementations for the Select dropdown (Semantic UI in our case).

Also added some documentation to the README and made the example use it as well.

### Linked Issues
#64

### CODE REVIEW

**Comment by ndom91** [comment]
Love this use-case! 

If you could take a look at the merge conflicts, we can get this merged soon.

Sorry its taken me forever to get back around to these!

**Comment by DreierF** [comment]
I rebased the changes on main.
The build is now also failing (just like main) because due to the `prepublishOnly` the `dist` folder is no longer built before running the tests.

I also got rid of the .d.ts files, because they just duplicate all the types with the `.ts` files. Is there any reason why those are checked in that I missed?

**Comment by ndom91** [comment]
Removed the `.d.ts` files and made `react-select` a peer dep in `2.0.0` (https://github.com/ndom91/react-timezone-select/pull/94) :partying_face: 

As soon as we get this PR out it should be good to go then :+1:

**Comment by ndom91** [comment]
Okay so tests pass, lets merge! :partying_face:

**Comment by ndom91** [comment]
Released in [`v2.1.0`](https://github.com/ndom91/react-timezone-select/releases/tag/v2.1.0). Thanks again! :pray:

**Pull request merged**
