### PR TITLE
fix: Gracefull Handling For Missing Timezones in timezone-soft library

### PR DESCRIPTION
**Pull request by salmanorak**
### Description

There are some timezones that timezone-soft library doesn't return an object of definitions for them. So in that case the current code is facing accessing a property of an undefined object. More details and screenshots of an error can be found in the linked issue notification.

As a solution, I have updated library versions and also added an optional chaining control while accessing a property of tzString objects.

### Linked Issues

https://github.com/ndom91/react-timezone-select/issues/76

### Additional context

- Abbreviation visibility was hard coded to a maximum of 5 characters. I made it configurable by adding a prop.

### CODE REVIEW

**Comment by ndom91** [comment]
Hey thanks for this! Will take a closer look soon

**Comment by salmanorak** [comment]
@ndom91 Is there any chance that You can review it today? 
I need to add a new feature and this issue stops me. If not please let me know I will switch to a fork package until we able to resolve it.

**Comment by ndom91** [comment]
@salmanorak alright so I went and added the test, but then I noticed that it'd be a bit easier to just wrap the body of that `reduce` in a `try`/`catch` and return the `selectOptions` early if theres an error

**Comment by ndom91** [comment]
However, I don't seem to be able to push to `github.com/salmanorak/react-timezone-select`. 

Can you check if you're allowing others to push to that branch / fork? Then I can push to this PR and we can merge :partying_face:

**Comment by salmanorak** [comment]
Ohh :) You are faster than me. You added tests and changed the implementation while I was adding test cases.

I have added You to the fork as a collaborator, and I have resolved the issue. Your solution is better I just don't want to change the implementation too much 😄 to not interfere with the current coding style.

**Comment by ndom91** [comment]
Alright, so it took a lot more little fixes than I imaged haha. But I've applied the best of both of ours now I think :crossed_fingers: 

I'll go ahead and merge this

**Pull request merged**
