### PR TITLE
Adding the ability to provide your own timezones

### PR DESCRIPTION
**Pull request by FreCap**

### CODE REVIEW

**Comment by ndom91** [comment]
Hi @FreCap thanks for the PR! I like the idea of being able to add your own timezone options, however in your implementation I was not able to get it to add another timezone. 

Maybe I'm misunderstanding, but do you want to provide a whole other version of the `i18nTimezones` object including every time zone? Or just provide the ability to add a few individual timezones? Because on line 90 you're defining the variable `timezones` which later gets reduced over, as _either_ the built-in `i18nTimezones` _or_ the prop provided `timezones` (i.e. `timezones = timezones || i18nTimezones`)

Suggestion: how about the following, on `index.js` line 90:

```js
timezones = timezones ? { ...i18nTimezones, ...timezones } : i18nTimezones
```

Therefore you could use it like so:

```jsx
<TimezoneSelect
  value={selectedTimezone}
  onChange={setSelectedTimezone}
  labelStyle={labelStyle}
  onBlur={() => console.log('Blur!')}
  timezones={{
    'America/Lima': 'Pittsburgh',
    'Europe/Berlin': 'Frankfurt',
  }}
/>
```

That way users can easily add custom timezone choices to the list. What this does not allow for, unfortunately, is replacing the entire `i18nTimezones` object with ones own. If that was your intent, then you'll have to show me how you planned to use the prop. I'm sure we can find a good middle ground!

To merge this, I'd also appreciate some text in the README describing the new prop and in which format to define custom timezones, etc.

**Comment by FreCap** [comment]
Hi @ndom91,

the intent is full replacement (e.g. if a company just wants to put a tiny list of supported timezones) and discard the ones not of interest.

For this reason I export the i18nTimezones in such a way if the user cares about those he/she could run:

`<TimezoneSelect
  value={selectedTimezone}
  onChange={setSelectedTimezone}
  labelStyle={labelStyle}
  onBlur={() => console.log('Blur!')}
  timezones={{
     ...i18nTimezones
    'America/Lima': 'Pittsburgh',
    'Europe/Berlin': 'Frankfurt',
  }}
/>`

**Comment by chrishrtmn** [comment]
I would love this option to allow a selection of allowed/selected timezones.

**Comment by ndom91** [comment]
@FreCap okay that makes sense. Lets do it that way then. Can you make a note in the docs maybe with an example or two showing how to completely provide your own timezone object, and then how you can use this new prop to just append some custom choices by importing `i18nTimezones` and appending your own choices like in your example in your latest comment.

Other than that it looks good to go in its current form!

**Comment by ndom91** [comment]
I've merged it and added the docs myself. Thanks for your contribution!

Now available on npm in `v0.9.11` :tada:

**Pull request merged**
